name: chatapp
description: A Chat App

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  styled_widget: "0.2.2"

  # Just Firebase Things
  firebase_core: "^0.5.2+1"
  firebase_auth: "^0.18.3+1"
  cloud_firestore: "^0.14.3+1"



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/graphics/
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Light.ttf
          weight: 300
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: fonts/Gilroy-ExtraBold.ttf
          weight: 800
    - family: JetBrainsMono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: fonts/JetBrainsMono-ExtraBold.ttf
          weight: 800
